# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latest_tweets', '0013_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='text',
            field=models.CharField(max_length=140),
        ),
    ]
